<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>io.github.easy4j</groupId>
		<artifactId>easypdf</artifactId>
		<version>2.0.x.20260730-SNAPSHOT</version>
	</parent>

	<artifactId>easypdf-webit</artifactId>
	<name>${project.groupId}:${project.artifactId}</name>
	<packaging>jar</packaging>
	<description>Webit template engine support for easypdf PDF generation</description>
	<url>https://github.com/easy-4-java/easypdf</url>
	<licenses>
		<license>
			<name>The Apache Software License, Version 2.0</name>
			<url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
		</license>
	</licenses>
	<scm>
		<connection>scm:git:https://github.com/easy-4-java/easypdf.git</connection>
		<developerConnection>scm:git:https://github.com/easy-4-java/easypdf.git</developerConnection>
		<url>https://github.com/easy-4-java/easypdf</url>
	</scm>
	<developers>
		<developer>
			<name>Loong Wan</name>
			<email>hiwepy@gmail.com</email>
			<url>https://github.com/loong10k</url>
		</developer>
	</developers>

	<dependencies>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>easypdf-core</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.github.zqq90.webit-script</groupId>
			<artifactId>webit-script</artifactId>
		</dependency>
	</dependencies>

</project>