<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>io.github.easy4j</groupId>
		<artifactId>easypdf</artifactId>
		<version>2.0.x.20260630-SNAPSHOT</version>
	</parent>
	
	<artifactId>easypdf-rythm</artifactId>
	<name>${project.groupId}:${project.artifactId}</name>
	<packaging>jar</packaging>

	<dependencies>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>easypdf-core</artifactId>
			<version>${project.version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.rythmengine/rythm-engine -->
		<dependency>
			<groupId>org.rythmengine</groupId>
			<artifactId>rythm-engine</artifactId>
		</dependency>
	</dependencies>

</project>